### ISSUE TITLE
[CLOUD]: Security changes response to /reports is `status` and should be `armed`

### ISSUE THREAD

**Issue by bjyurkovich** [technicity/connnected-vessel#3]
When I `POST /changes` to arm/disarm the security system, my `POST` looks like this:

``` json
{"id": "1", "type": "security", "profileId": "kraken-001", "armed": true}
```

Then, the hub calls `https://mercury.vesselviewmobile.com/kraken/api/v1/hubs/kraken-001/reports`, and this is returned:

``` json
[{
    "id": "1",
    "type": "security",
    "status": null,
    "profileId": "kraken-001"
  }]
```

The `status` field should be `armed`.

FYI @coryott

**Comment by poehler** [comment]
@bjyurkovich  I'm going to also guess that the value in the message should also be true and not null

`[{
    "id": "1",
    "type": "security",
    "armed": true,
    "profileId": "kraken-001"
  }]`

**Comment by pavcenteno1** [comment]
After calling /reports I get this message, armed is part of Report_data_security. I don't see the returned messages [{
    "id": "1",
    "type": "security",
    "status": true,
    "profileId": "kraken-001"
  }]: 




https://mercury.vesselviewmobile.com/kraken/api/v1/hubs/kraken-001/reports
{
  "profileId": "kraken-001",
  "timestamp": 1476373690,
  "data": {
    "bilge": [
      {
        "duration": 5,
        "id": "Bilge1",
        "status": null
      }
    ],
    "light": [
      {
        "id": "Port",
        "status": null
      },
      {
        "id": "Starboard",
        "status": null
      }
    ],
    "bms": null,
    "security": {
      "id": "Security1",
      "armed": false,
      "lastImage": ""
    },
    "shorePower": {
      "id": "ShorePower",
      "status": false,
      "duration": 0
    }
  },
  "gps": {
    "lat": 44.247414,
    "long": -88.488815
  },
  "currentAlerts": null
}

**Comment by bjyurkovich** [comment]
@pavcenteno1 are you calling `https://mercury.vesselviewmobile.com/kraken/api/v1/hubs/kraken-001/changes` first?  When you do, and then call `/reports`, I the hub should get back:

```json
[{
"id": "1",
"type": "security",
"**armed**": true,
"profileId": "kraken-001"
}]:```

not

```json
[{
"id": "1",
"type": "security",
"**status**": true,
"profileId": "kraken-001"
}]:
```

**Comment by bjyurkovich** [comment]
@poehler yep...I figure that is a side effect of the mismatched field name `status` vs `armed`

**Comment by pavcenteno1** [comment]
Yes...I did.....that's why I'm confused because I don'g get the same result

**Comment by pavcenteno1** [comment]
@bjyurkovich call to https://mercury.vesselviewmobile.com/kraken/api/v1/hubs/kraken-001/changes POST or GET?
If is a post, can you provide the object. 
If is a GET....I got this:
{
  "profileId": "kraken-001",
  "timestamp": 1476373690,
  "data": {
    "bilge": [
      {
        "duration": 5,
        "id": "Bilge1",
        "status": null
      }
    ],
    "light": [
      {
        "id": "Port",
        "status": null
      },
      {
        "id": "Starboard",
        "status": null
      }
    ],
    "bms": null,
    "security": {
      "id": "Security1",
      "armed": false,
      "lastImage": ""
    },
    "shorePower": {
      "id": "ShorePower",
      "status": false,
      "duration": 0
    }
  },
  "gps": {
    "lat": 44.247414,
    "long": -88.488815
  },
  "currentAlerts": null
}

**Comment by pavcenteno1** [comment]
It seems is a POST....

**Comment by pavcenteno1** [comment]
@poehler The object is a Command object. But the spec does not say "armed", it says status, instead.
Shall I change the field name?

{
"id": "1",
"type": "security",
"armed": true,
"profileId": "kraken-001"
}

**Comment by pavcenteno1** [comment]
This has been fixed...please try again

**Comment by bjyurkovich** [comment]
Looks good. thanks!

**Comment by bjyurkovich** [comment]
@pavcenteno1 Reopening because while it looks like the `security` type was fixed, the `light` type now looks like this on the response to a `POST /report`:

```json
[
  {
    "id": "1",
    "type": "light",
    "armed": null,
    "profileId": "kraken-001"
  }
]
```

**Comment by bjyurkovich** [comment]
closing to open new issue
