### ISSUE TITLE
[CLOUD]: command status shows NULL

### ISSUE THREAD

**Issue by mjfalcone90** [technicity/connnected-vessel#5]
@poehler @pavcenteno1  we are getting commands form the cloud as expected, but the status field of the command appears to be NULL. (instead of the expected true or false)

**Comment by bjyurkovich** [comment]
I also noticed this....see #3

**Comment by pavcenteno1** [comment]
@mjfalcone90 are you getting "armed" instead of "status"?

**Comment by pavcenteno1** [comment]
@mjfalcone90 can you provide an example of the message that you are sending?

**Comment by mjfalcone90** [comment]
i was getting null instead of status.  and when you say sending do you mean from the hub or how i am sending the command?

**Comment by pavcenteno1** [comment]
@mjfalcone90 Yeah..I want to reproduce the issue....so I might need the message you are sending to produce the issue

**Comment by pavcenteno1** [comment]
@mjfalcone90 I've added "status" to the command entity. 
Please try again and let me know if that works.
