### ISSUE TITLE
[CLOUD]: Security object on MQTT network still uses "armed"

### ISSUE THREAD

**Issue by bjyurkovich** [technicity/connnected-vessel#6]
Currently, I am getting still getting a security object from a hub `report` that still has `armed` instead of the desired `status` field dictating its state.  It should have `status` instead of `armed`.

@coryott may be involved here, too, in the event that he is still sending `armed` from the hub (not sure how the cloud implements this).

**Comment by pavcenteno1** [comment]
I've updated the Security object, it uses status again

**Comment by coryott** [comment]
I still had `armed` in the security portion of `/report`. It has been changed to `status`
